### ISSUE TITLE
qrcode generated bug

### ISSUE THREAD

**Issue by xgqfrms** [scopewu/qrcode.vue#10]
# qrcode generated bug

> some url can't be open by scan the qrcode generated by the mobile phone

1. demo bug

![image](https://user-images.githubusercontent.com/7291672/56878863-c1247800-6a88-11e9-9f04-808193abd999.png)

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/56879215-36dd1380-6a8a-11e9-8e97-72b9359f2c43.png)

**Comment by xgqfrms** [comment]
https://github.com/defunctzombie/qr.js

**Comment by scopewu** [comment]
Hello, what is the text content of qrcode?

**Comment by xgqfrms** [comment]
@scopewu that is an URL with some Chinese characters.

`https://m.weibo.cn/search?containerid=231522type%3D1%26q%3D%23长沙高质量发展调研行%23&from=singlemessage&display=0&retcode=6102`

**Comment by xgqfrms** [comment]
# set level =`L`  will be ok.
