### ISSUE TITLE
尺寸设置不一致

### ISSUE THREAD

**Issue by xdw898618984** [scopewu/qrcode.vue#12]
设置的尺寸与显示的尺寸不一致
private sizes:any= 320; // 二维码尺寸
private bgColor:any = '#fff'; // 二维码背景色
private fgColor:any = '#000'; // 二维码码条颜色
private http:string = '';// 生成的二维码网址、

**Comment by xdw898618984** [comment]
显示的尺寸是287px

**Comment by scopewu** [comment]
Hi @xdw898618984:
请告知浏览器和操作系统版本，在我的电脑（Windows10 chrome 78/79 和 Edge 18）中测试正常。

**Comment by xdw898618984** [comment]
![image](https://user-images.githubusercontent.com/29720056/70872694-e993bf00-1fe4-11ea-8580-ba44569b20f5.png)

**Comment by xdw898618984** [comment]
window 10，在我本机测试也无异常，测试电脑有异常
![image](https://user-images.githubusercontent.com/29720056/70872765-38d9ef80-1fe5-11ea-895c-90d0a6f724d6.png)

**Comment by xdw898618984** [comment]
原因是测试缩放屏幕尺寸！

**Comment by scopewu** [comment]
> 原因是测试缩放屏幕尺寸！

一直未回复的原因是就上面获取的信息没有找到问题原因，明天（2019-12-18）到公司确认屏幕尺寸是否影响。
感谢一直沟通回复 😘。
