### ISSUE TITLE
建议增加一个增加二维码边的间距

### ISSUE THREAD

**Issue by larvacent** [scopewu/qrcode.vue#13]
建议增加一个增加二维码边的间距，比如生成的画布是 500px,可以设置成 二维码490,10作为背景的边，不要占满画布

**Comment by scopewu** [comment]
@larvacent 过去考虑过，想来用户可以使用样式自定义边距、边框、二维码中部修饰图片等等，看来需求还是有的，后面的版本考虑加入。感谢反馈 👍

**Comment by codymikol** [comment]
I've seen other projects support a :padding binding, but I'd rather use css explicitly as it's easier to customize.
