### ISSUE TITLE
Is there any way to download the QR as an image?

### ISSUE THREAD

**Issue by Adrek** [scopewu/qrcode.vue#14]
First, congratulations to you for your bookstore, it fulfills its objective very well.

My question is: is there any way to download the QR as an image?
I would like to add a button that, when clicked, downloads the same QR code but as an image.

Thank you very much.

**Comment by scopewu** [comment]
Hi,
  `qrcode.vue` just generate QRCode. The download function needs to be implemented by yourself, you can refer to [stackoverflow.com](https://stackoverflow.com/questions/8126623/downloading-canvas-element-to-an-image#answer-42546234).
  Need to pay attention to vue status update synchronization, the [Vue.nextTick](https://vuejs.org/v2/api/index.html#vm-nextTick).
