### ISSUE TITLE
renderAs props is not working after deployments

### ISSUE THREAD

**Issue by enkhtulga-tulgaa** [scopewu/qrcode.vue#17]
First of all, thank you to make this awesome qrcode plugin. 

I need to render QRCODE as svg using renderAs props. It works fine on localhost. but it does not work after deployment. I look up the issue.  After deployments renderAs props is not on props list it's on attr . I have attached my local & develop screenshots below. 

![0101](https://user-images.githubusercontent.com/54702277/73149249-4eb9f480-40fb-11ea-9a10-40c3957eda06.PNG)
![0102](https://user-images.githubusercontent.com/54702277/73149250-4f528b00-40fb-11ea-8138-0a9a5fd98add.PNG)

**Comment by scopewu** [comment]
Hi,
  I have received this feedback, checked possible causes, and tried to fix it.
  I'm sorry that this time is in the Chinese New Year, so it is a bit late to deal with the issue.
