### ISSUE TITLE
safari浏览器二维码尺寸失效

### ISSUE THREAD

**Issue by xdw898618984** [scopewu/qrcode.vue#18]
![image](https://user-images.githubusercontent.com/29720056/75314421-a97d7200-589a-11ea-84a7-e96f14e8f8e2.png)
![image](https://user-images.githubusercontent.com/29720056/75314455-c1ed8c80-589a-11ea-812b-c4fbf5bfbf8e.png)
![image](https://user-images.githubusercontent.com/29720056/75314516-eb0e1d00-589a-11ea-9c60-685e2a3a1632.png)

尺寸设置为320

**Comment by xdw898618984** [comment]
图片尺寸还是默认得640px

**Comment by scopewu** [comment]
检查下是不是自定义样式影响宽度；在高清屏中宽度会 size * (window.devicePixelRatio || 1)；
也可以快捷尝试 `render-as=svg`；
后期维护的时候测试临界值，加强处理各种边界情况。

**Comment by xdw898618984** [comment]
方便加个微信吗xdw898618984,我是设置了自定义的canvas尺寸，在chrome和其他浏览器没有什么问题
