### ISSUE TITLE
怎么可以下载qrcode

### ISSUE THREAD

**Issue by dannykhoo** [scopewu/qrcode.vue#21]
不好意思，新手一个，该怎么下载这个qrcode呢，谢谢

**Comment by scopewu** [comment]
可以尝试 `canvas` 的 `.toDataURL` 方法：更多参考 [stackoverflow.com](https://stackoverflow.com/questions/8126623/downloading-canvas-element-to-an-image#answer-42546234)

same issue #14

**Comment by dannykhoo** [comment]
好的谢谢！
