### ISSUE TITLE
Is there any way to download generated QR code?

### ISSUE THREAD

**Issue by Cozy-Ho** [scopewu/qrcode.vue#22]
I wander,
can I download QR code as JPG or any image file format.

**Comment by scopewu** [comment]
@Cozy-Ho Hi, you can try the `.toDataURL` of `canvas`. Looking more info on [stackoverflow.com](https://stackoverflow.com/questions/8126623/downloading-canvas-element-to-an-image#answer-42546234)

same issue: #14

**Comment by Cozy-Ho** [comment]
Thanks  👍 
I'll close this issue
