### ISSUE TITLE
Download the qr as png, jpg...

### ISSUE THREAD

**Issue by demiremredev** [scopewu/qrcode.vue#23]
How to download it from my parent component

**Comment by scopewu** [comment]
Hi, you can try the `.toDataURL` of `canvas`. Looking more info on [stackoverflow.com](https://stackoverflow.com/questions/8126623/downloading-canvas-element-to-an-image#answer-42546234)

**Comment by demiremredev** [comment]
The canvas element is in subcomponent because of this reason I could not reach that canvas element.

**Comment by scopewu** [comment]
Yes, now just can use `document.querySelector('.qrcode canvas')` to get the element.

Downloading QR codes might be a feature to implement in the future.

**Comment by demiremredev** [comment]
Thanks
