### ISSUE TITLE
Not Vue3 compliant?

### ISSUE THREAD

**Issue by leolivier** [scopewu/qrcode.vue#25]
Hi @scopewu 

When trying to use qrcode-vue in a Vue3 project I get the following error 
`Uncaught (in promise) TypeError: createElement is not a function
`
Other vue components having the same error say it is because they are not vue3 compliant.

**Comment by scopewu** [comment]
Hi @leolivier
Now releasing new version (3.0.0) to add feature support, please try to upgrade.

**Comment by leolivier** [comment]
Thanks @scopewu
I wrote my own very simple one meanwhile.
I'll try yours asap
