### ISSUE TITLE
feature: 支持以 img 标签形式展示

### ISSUE THREAD

**Issue by henrycjchen** [scopewu/qrcode.vue#29]
## 场景：
微信页面长按识别二维码

## 存在问题
当前组件只支持生成 canvas 和 svg，然而微信只支持 img 标签长按识别

## 希望解决方案
希望该组件支持 img 标签展示

**Comment by scopewu** [comment]
Hi @henrycjchen 一个临时的方案是使用 `canvas` 的 `.toDataURL("image/png")` 方法。类似于：

```js
const canvas = document.querySelector('canvas);
const png = canvas.toDataURL("image/png");

const img = document.createElement('img');
img.src = png;
document.body.appendChild(img);
```

未来有时间可能考虑支持功能，谢谢提出 issue。
