### ISSUE TITLE
How many Maximum Character support?

### ISSUE THREAD

**Issue by githubgobi** [scopewu/qrcode.vue#3]
how much Maximum alpha numeric character using this package?

**Comment by scopewu** [comment]
@githubgobi Uncompressed version is 26 kb, You can webpack(or other tool) UglifyJsPlugin little for app.

**Comment by scopewu** [comment]
The next release I will add a compressed version

**Comment by githubgobi** [comment]
what is  maximum length of character for qr code generator?

**Comment by scopewu** [comment]
@githubgobi You can look at http://www.qrcode.com/en/codes/

**Comment by scopewu** [comment]
Can also be tested at  https://scopewu.github.io/qrcode.vue/
