### ISSUE TITLE
Single File componet: Vue is not defined

### ISSUE THREAD

**Issue by jg4smile** [scopewu/qrcode.vue#31]
Good afternoon.

Whenever we attempt to integrate QrcodeVue into a single-file component, we receive the error "Vue is not defined". We're certainly not veterans of VueJS, but we have been able to create custom components and get them to work. below is our attempt at the SFC implementation: 

`<template>
  <qrcode-vue :value="value" :size="size" level="H" />
</template>
<script>
  import QrcodeVue from 'qrcode.vue'

  export default {
    data() {
      return {
        value: 'https://example.com',
        size: 300,
      }
    },
    components: {
      QrcodeVue,
    },
  }
</script>
`

We are using Vue 3.X. We have a "components" directory with the code above. We have made the changes to "vue.config.js" as instructed, and we don't have a "webpack .config.js", but rather an "intellij.config.js" (added the resolve clause here), and when attempting to integrate with Ionic Vue "ionic.config.js (did not add resolve clause here) and babl.config.js (did not add resolve clause here). any help would be greatly appreciated. Thanks.

**Comment by scopewu** [comment]
Hi @jg4smile,
    vue cli now uses `package.browser` by default, and the current `qrcode.vue` package.browser is built based on iife, which causes Vue undeclared errors due to module loading. Try using the following configuration in `vue.config.js` or upgrade `qrcode.vue` to `3.2.2`, which uses the umd build.  

```js
module.exports = {
    configureWebpack: {
        resolve: {
            alias: {
                'qrcode.vue$': 'qrcode.vue/dist/qrcode.vue.esm.js'
            }
        }
    }
}
```
