### ISSUE TITLE
Can the width be string?

### ISSUE THREAD

**Issue by patchthecode** [scopewu/qrcode.vue#34]
i have put 

```
size="100vw"
```

This works perfectly, but i get a warning error. Can this warning be removed?

**Comment by scopewu** [comment]
Hi @patchthecode ,
  `qrcode.vue` uses pixels as the unit of width and height. The `size` prop will try to convert to a number, so `'100vw'` will be `0`. Vue will check the type definition during development, so try using the dynamic prop `:size='100'` to remove the warning.

**Comment by scopewu** [comment]
The issue will be closed.
