### ISSUE TITLE
How to Redraw?

### ISSUE THREAD

**Issue by goldenfreemanchina** [scopewu/qrcode.vue#4]
RT....

**Comment by scopewu** [comment]
Two-way binding can be running on vue.js component.
```js
import Vue from 'vue';
import QrcodeVue from 'qrcode.vue';

new Vue({
  el: '#root',
  data: {
    value: 'https://example.com'
  },
  template: '<qrcode-vue :value="value"></qrcode-vue>',
  components: {
    QrcodeVue
  },
  methods: {
    changeValue() {
        this.value = 'https://scopewu.github.io/qrcode.vue/'
    }
  }
})
```
Change data `value` to update view. Like run `this.changeValue()`
See: https://scopewu.github.io/qrcode.vue/
It is a vue.js component for qrcode. You can see the document https://vuejs.org/v2/guide/components.html.

`vue.js` 组件支持双向数据绑定，数据改变会触发视图更新.
在上面的例子中，运行组件的`changeValue`方法会将二维码的值更新。
也可以更新为指定的文本。
```js
changeValue(text) {
  this.value = text
}
```

**Comment by scopewu** [comment]
Any questions? I will close this issue.
