### ISSUE TITLE
margin is not work in vue2 with 1.7.0

### ISSUE THREAD

**Issue by jiameiw** [scopewu/qrcode.vue#41]
```
<qrcode-vue
        :value="value"
        :size="430"
        level="H"
        :margin="30"
      >
      </qrcode-vue>
```
but get 
![image](https://user-images.githubusercontent.com/24668268/134345279-6e4aa9f7-5884-4b60-988c-5db847c1f5ad.png)

**Comment by scopewu** [comment]
Hi @jiameiw, The qrcode `1.7.0` does not support the margin prop, `3.1.0` was the first version to support it (vue3 only). Maybe support will be added in the future, would using css padding be sufficient?

**Comment by jiameiw** [comment]
> Hi @jiameiw, The qrcode `1.7.0` does not support the margin prop, `3.1.0` was the first version to support it (vue3 only). Maybe support will be added in the future, would using css padding be sufficient?

ok,thanks

**Comment by SRichner** [comment]
It would be great to have this for Vue 2 as well.
In the meantime, a note in the readme that this is currently not supported would be nice.

**Comment by scopewu** [comment]
Next I'll try to support `margin` and `image` in vue2.

**Comment by mikefress** [comment]
I Also had the same issue.

**Comment by BTMuli** [comment]
Vue2 is EOL soon...so why not upgrade to vue3？

**Comment by scopewu** [comment]
`VUE 2.x` end of life.
