### ISSUE TITLE
Level 'M' and 'H' have the same performance

### ISSUE THREAD

**Issue by gadfly3173** [scopewu/qrcode.vue#45]
level设置M H出现的二维码完全相同，演示页和自己安装的都是这样。
![image](https://user-images.githubusercontent.com/28685179/137475971-e38ec115-d5ac-40c1-a766-7af5969e8093.png)
![image](https://user-images.githubusercontent.com/28685179/137475987-b7fccf49-0b39-4360-8413-d49dac4504f3.png)

**Comment by scopewu** [comment]
Hi @gadfly3173, 代码中处理错误级别的处理方式确实有误，版本 `3.3.3` 将修复。

最近有一些事情需要处理，很抱歉没有及时处理 issue，感谢提交 issue，3Q

**Comment by scopewu** [comment]
The issue was fixed `v3.3.3`.
