### ISSUE TITLE
Vue parameter for value issue

### ISSUE THREAD

**Issue by ravenshore** [scopewu/qrcode.vue#49]
Hi, again,

I just realized that when I try to use the Vue parameter as value, instead of hardcoded text I am getting an error. I even tried to set a condition to make sure that the element doesn't load if the value is not set, however it seems the library is having an issue. Not sure how to proceed:
![image](https://user-images.githubusercontent.com/9301154/142966146-7d88c295-63fb-483d-ab60-e093452fae90.png)
![image](https://user-images.githubusercontent.com/9301154/142966190-f7562a9b-5f2a-4ca7-8c28-8628c1981df0.png)
If I return to a simple string error goes away: 
![image](https://user-images.githubusercontent.com/9301154/142966228-5efb8345-6ee4-4f24-b1df-1ef4f60404af.png)

I tried using computed property, data linked to computed and data with a deep watch on it, but nothing worked.
Any ideas are appreciated!

Thanks!

**Comment by scopewu** [comment]
`value` should be a `string`, if not a `truly`. yes, if not, the `v-if` judgment can hide the `qrcode`:
```js
<qrcode-vue v-if="plate" id="qrcode" :value="plate" />
```

**Comment by ravenshore** [comment]
Thanks! I was able to work around that by still pointing it do the computed value, but forcing the type to string like:
```
plate() {
            let plate = "Not Logged In"
            if (this.status) {
                plate = "" + this.$store.state.plate
            }
                return plate
        },
```

Otherwise the plate itself does return a string, as I am using it for other things, however it seems that the type has to be explicit.
You could close the issue if you'd like.
Thanks!
