### ISSUE TITLE
Vue 2.6.14 and qrcode.vue 1.7.0 Unknown custom element:

### ISSUE THREAD

**Issue by scorpioRED** [scopewu/qrcode.vue#56]
Hi! I'm trying to use your Library but got an error
`Unknown custom element: <qrcode-vue> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Hover, I made
 `import QrcodeVue from 'qrcode.vue';` 
and 
```
export default {
  name: "MyComponnent",
  comments:{
    QrcodeVue
  },.....
```
 in my Component.

I even also tried adding to main.js

```
import QrcodeVue from "qrcode.vue";

Vue.use(router, QrcodeVue)
```
What  I did do wrong?

package.json
```
...
  "dependencies": {
    "axios": "^0.27.2",
    "core-js": "^3.8.3",
    "qrcode.vue": "^1.7.0",
    "vue": "^2.6.14",
    "vue-axios": "^3.4.1",
    "vue-router": "^3.5.4",
    "vuetify": "^2.6.0",
    "vuex": "^3.6.2",
    "vuex-persistedstate": "^3.2.1"
  },
....
```

**Comment by scopewu** [comment]
Hi，
In the example you have written, the component field name is written incorrectly. Try correcting the `comments` to `components`.

```vue
export default {
  name: "MyComponnent",
  comments: {              // Try correcting it to `components`
    QrcodeVue
  },.....
```
When you create a global component, can read the Vue's docs:
Vue 2: https://v2.vuejs.org/v2/guide/components-registration.html
Vue 3: https://vuejs.org/guide/components/registration.html

**Comment by scopewu** [comment]
Hi，Have any questions? The issue will be closed.
