### ISSUE TITLE
vue3 使用报警，二维码显示不出来

### ISSUE THREAD

**Issue by laowangdefangjian** [scopewu/qrcode.vue#59]
报警信息：Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function.
备注:在defineComponent里注册的组件

**Comment by scopewu** [comment]
@laowangdefangjian `qrcode.vue` 的版本是 `3.3.3` 吗？可以的话麻烦提供使用 `Vue` 和 `qrcode.vue` 版本，以及部分关键代码。单靠上面的报错无法判定是何种原因。

**Comment by laowangdefangjian** [comment]
**//版本**
`"qrcode.vue": "^3.3.3",` 
**//js**
import QrcodeVue from 'qrcode.vue'
`export default defineComponent({ 
  components: {
    QrcodeVue
  },
  setup (props, ctx) {
    const state = reactive({
      shareUrl: 'https://www.baidu.com/',
      size: 110,
    })
    return {
      ...toRefs(state)
    }
  }
})`
**//html**
<QrcodeVue :value="shareUrl" :size="size" level="H"></QrcodeVue>

**Comment by laowangdefangjian** [comment]
**//版本**
`"qrcode.vue": "^3.3.3",` 
**//js**
import QrcodeVue from 'qrcode.vue'
`export default defineComponent({ 
  components: {
    QrcodeVue
  },
  setup (props, ctx) {
    const state = reactive({
      shareUrl: 'https://www.baidu.com/',
      size: 110,
    })
    return {
      ...toRefs(state)
    }
  }
})`
**//html**
<QrcodeVue :value="shareUrl" :size="size" level="H"></QrcodeVue>

**Comment by scopewu** [comment]
@laowangdefangjian 你好，由于示例代码不全不足以判断。这里有一个与你的代码相似的[效果演示](https://sfc.vuejs.org/#eNp1UktvnDAQ/itTX9hIuzhtb4hErSpVvfZQ9cKFwuzGkV87NrQq4r9nbCDazQMkzDePb2a+8SS+el+OA4pK1KEj5SPo1p7uGhFDI+4bq4x3FGGCHo/K4jfH2KKNeyA8pk/bRTUizHAkZ6BgrqKxAGveT+pcj6vvTOxqLP7LLiZsB53PS+LdlNK7DYaKa68s8z65AsbB7zx5F24gB6dwGyKYcIK71Neu+IFaO/jtSPcfipvLoDN9d/SLdI5cmt9NMJCuoHiI0YdKynDskiiPoXR0KmBeCYgrk91qQqqXO0rPRrvgOR38SZm1XIRlMRlENF63ERkB1A8f76cp9z3PtWSUrcr6IcJ4MDy05lWwP++CXV4u56pINbZ6wC0EqqD+J/Tp9pYRoe2RDm1gSxjZv+a+x7GNULIYS3Atn9sVe7Gs9GBaXz4GZ/nKZCWa1cH3hXe1zN8Ili/hRrypqeS/kgYblcESgzn8Ifc3IDFxI1ZNU0PXFF1vOYA1USOVFqO03shzniJRf/lc8it7FeKFNdFf07JRcq2RtVkkwhd1rlt9Efqq3W3VYn4ClMAd+w==)，希望对你有帮助。

**Comment by laowangdefangjian** [comment]
请问以上代码需要下载哪些依赖呢？我下载了qr+util+child_process，只要引入import Qrcode from 'qr'就会报Module not found: Error: Can't resolve 'child_process' in 'D:\project\fengyuan-tech\node_modules\_qr@0.2.4@qr\lib'
谢谢

**Comment by scopewu** [comment]
> 请问以上代码需要下载哪些依赖呢？我下载了qr+util+child_process，只要引入import Qrcode from 'qr'就会报Module not found: Error: Can't resolve 'child_process' in 'D:\project\fengyuan-tech\node_modules_qr@0.2.4@qr\lib' 谢谢

抱歉**示例代码**的依赖导入使用了简写，如果使用 `webpack` 等同于 `import QrcodeVue from 'qrcode.vue'`，不是 `qr+util+child_process`。
```json
{
  "imports": {
    "vue": "https://sfc.vuejs.org/vue.runtime.esm-browser.js",
    "qr": "https://cdn.jsdelivr.net/npm/qrcode.vue@3.3.3/dist/qrcode.vue.esm.js",
    "vue/server-renderer": "https://sfc.vuejs.org/server-renderer.esm-browser.js"
  }
}
```

**Comment by scopewu** [comment]
[效果演示](https://sfc.vuejs.org/#eNp9Uk1vnDAQ/StTX9hIuzhtb4hErSpVvfZQ9cKFwuzGkb8yNrQq4r9nbCDZfIKEeZ7nNzNvPImv3pfjgKISdehI+Qi6taerRsTQiOvGKuMdRZigx6Oy+M0xtmjjHgiP6dN2UY0IMxzJGShYq3g49ZM61+MaucsgJWNCY/FfprBsO+i8nsvvpsYCdBsMFVewqs37FAoYB7/z5F24gExOdBsimHCCq1TdrviBWjv47Uj3H4qLc9IdfXf0i3RmLi3sJhhIV1DcxOhDJWU4dqna21A6OhUwrwLEmcluOSHlyxWlZ5Nd8JwW/qSTtVzsZUsZRDRetxEZAdQ3H6+nKdc9z7VklHeV9UOE8WC4ac0D4XieCIe8XNbVkWps9YAbBaqg/if06fKSEaHtkQ5t4J0wcnw9+5bG1kLJZizkWj6UK/ZiGe3BtL68Dc7yxclONGuAbw3Paum/EWxfwo141VPJfyUNNiqDJQZz+EPub0Bi4UasnqaCtnvzVKrrLRPZGzVSaTFK6418JH/5XPIrexXi2W5K81SeNyXnHNmjxSqk90p+Rn1R9jZyMd8DCwEj7Q==)

**Comment by laowangdefangjian** [comment]
老师您好，请问render-as="svg"的二维码在vue上如何下载到本地呢？

**Comment by scopewu** [comment]
`render-as="canvas"` 是默认渲染方式，`canvas` 可以作为图片下载，具体参考 #14 和 #50。但设置 `render-as="svg"` 将以内嵌 `svg` 渲染，可以尝试搜索下载 `svg` 内容，查询是否有方法。

**Comment by scopewu** [comment]
如果没有更多问题，将关闭 issue.

The issue will be closed.
