### ISSUE TITLE
Export type `Level`.

### ISSUE THREAD

**Issue by DiscreteTom** [scopewu/qrcode.vue#65]
Currently the type `Level` is not exported, thus there will be a type error in TypeScript.

E.g.:

```vue
<template>
    <qrcode-vue  :level="level" />
</template>    

<script setup lang="ts">
import QrcodeVue from "qrcode.vue";
const level = ref("H");
</script>
```

Got: `Type 'string' is not assignable to type 'Level | undefined'.`.

**Comment by scopewu** [comment]
Hi,
Please upgrade the version to `3.4.1`. Now, the type named `Level` and `RenderAs` will be export.
