### ISSUE TITLE
firefox 火狐下打印预览二维码显示黑块

### ISSUE THREAD

**Issue by BlazingCC** [scopewu/qrcode.vue#66]
火狐浏览器，打印预览，二维码部分显示成了黑块
复现的话可以使用官方的这个页面，测试火狐为最新版本，系统为windows10
https://qr-vue.tie.pub/ 默认示例即可
我调了一下，把 d="M0,0 h25v25H0z" 修改为 d="M0,0 h25v25z" 就能正常显示，对SVG不了解。
希望作者可以帮忙看看

![屏幕截图 2023-08-23 094346](https://github.com/scopewu/qrcode.vue/assets/22879023/0335da6f-0c60-4b63-9373-d593d0418590)

**Comment by scopewu** [comment]
你好 @BlazingCC ，确认 `Firefox` 确实存在“背景颜色”打印问题，在打印面板中勾选 `更多设置 > 选项 > 打印背景` 可以正常打印。`Chrome` 默认勾选该选项，若不勾选结果与 `Firefox` 相同的黑色，后面尝试了解浏览器打印 `svg` 的细节。
