### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to resolve module specifier "qrcode.vue". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by Leezgion** [scopewu/qrcode.vue#68]
vite+TS+Vue3项目下
问题描述
>本地 npm run dev    "vite" 运行无异常，可以正常渲染组件,
> npm  run serve "vite preview" 以及 线上部署环境  控制台会报如下异常
![image](https://github.com/scopewu/qrcode.vue/assets/68184370/c7118d2e-a256-41ed-8726-b2c9935a224d)
> 由于组件问题导致路由无法跳转以及正常展示

以下是本人项目安装qrcode.vue操作
```
//安装库
npm i qrcode.vue
// ***.vue文件中 引入qrcode.vue
import QrcodeVue from 'qrcode.vue'
impoirt {ref} from 'vue'
//<template></template>代码简单样例代码
<qrcode-vue :value="text" :size="80" level="H" />
let text=ref('')
//vite.config.ts文件 *已隐藏其他配置*
- build `模块`
  - rollupOptions `选项`
    - external:['qrcode.vue']
```
以上大致就是情况复现 ，请问如何解决这个问题呢

**Comment by scopewu** [comment]
你好，rollup 的 `external` 字段表示的是在最终的[打包中不包含匹配项](https://cn.rollupjs.org/configuration-options/#external) 请更改配置为 `external: []`，或者其他你不想包含的包。

**Comment by Leezgion** [comment]
> 你好，rollup 的 `external` 字段表示的是在最终的[打包中不包含匹配项](https://cn.rollupjs.org/configuration-options/#external) 请更改配置为 `external: []`，或者其他你不想包含的包。

非常感谢您的解惑! 由于我们多人协同的配合失误，以及个人的vite知识有待提升🥺，现在问题已经解决，感谢~
