### ISSUE TITLE
Generated QR Code is different from one browser to another

### ISSUE THREAD

**Issue by SDVII** [scopewu/qrcode.vue#7]
Firefox:

![image](https://user-images.githubusercontent.com/10416702/52275223-f6c13580-295f-11e9-8882-dde0468475f1.png)

Chrome:

![image](https://user-images.githubusercontent.com/10416702/52275242-0a6c9c00-2960-11e9-955c-37773357acdb.png)

**Comment by xgqfrms** [comment]
@SDVII  this is bug, I think.
