### ISSUE TITLE
Package does not provide an export named 'Level'

### ISSUE THREAD

**Issue by Muhammad-shaalan** [scopewu/qrcode.vue#72]
Hi all,

I am using the "qrcode.vue": "^3.4.1",for "vue": "^3.4.14",  "nuxt": "^3.10.1",
I get this error when try destruct {Level}: import QrcodeVue, { Level, RenderAs } from 'qrcode.vue'
Uncaught (in promise) SyntaxError: The requested module '/_nuxt/node_modules/.cache/vite/client/deps/qrcode__vue.js?v=4e6d594e' does not provide an export named 'Level'

**Comment by scopewu** [comment]
The `Level` and `RenderAs` properties are intended for TypeScript. Again, please check if caching has any effect.

```ts
export type Level = 'L' | 'M' | 'Q' | 'H'
export type RenderAs = 'canvas' | 'svg'
```
