### ISSUE TITLE
QRCode does not render on page

### ISSUE THREAD

**Issue by zenute** [scopewu/qrcode.vue#74]
I have just upgraded a pwa from vue 2 to vue 3, and in consequence qrcode.vue to 3.4.1.
Some users can´t see the generated QRCode on theirs phones.
Sometimes, if the browser data is cleaned, the problem goes away, but sometimes not. 
I have hundreds of angry users , sending messages to our support team.
Can someone, please, help? Any idea of what might be the problem?

**Comment by scopewu** [comment]
Try debugger to determine if it is a resource module loading issue, browser version.

**Comment by zenute** [comment]
In dev it works all fine.
On my phone, there was no issues. It works as expected.
It seems, that when the user is upgrading to the vue3 version with qrcode 3.4.1, the browser somehow can´t update properly. Hence, the need to clean the pwa history and data.
That´s the solution we have found.
Thanks.
